name: Publish Package to npmjs
on:
  push:
    branches:
      - master
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - name: actions checkout
        uses: actions/checkout@v3
      - name: node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          scope: '@octocat'
      - name: Install & Build & Deploy
        run: | 
          yarn
          yarn build
          arn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  storybook-publish:
    needs: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: actions checkout
        uses: actions/checkout@v3
      - name: Install & Build 
        run: |
          yarn
          yarn build:storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
          CLEAN: true
          TARGET_FOLDER: stories